
import type { Metadata } from "next";
import Provider from "./provider";

export const metadata: Metadata = {
  title: "PseudoBoard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider>
            {children}
        </Provider>
      </body>
    </html>
  );
}
